version: '3.7'
networks: 
    dockerserver:
        driver: bridge
services:
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./app:/app
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks: 
            - dockerserver
    php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        volumes:
            - ./app:/app
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - dockerserver
    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: default
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_USER: guest
            MYSQL_PASSWORD: guest
        networks: 
            - dockerserver
